### PR TITLE
New Skin server and Username Capitaling

### PR DESCRIPTION
**Pull request by ItsLukeJames**
Hi, I changed it to the correct skin server and added and username case fixer.

This is completely untested code, I edited it from a project I started a while ago: https://github.com/tenten8401/MineAvatar

### CODE REVIEW

**Comment by jamiebicknell** [comment]
Thanks for the PR, but the problem with the new URL is that it requires CURL FOLLOW_LOCATION to be enabled, and allowed on the server. You see http://skins.minecraft.net/MinecraftSkins/jamiebicknell.png redirects to http://textures.minecraft.net/texture/3c8bd98d9d5d3912c9f7e925bcd88abecc4c32bcc57972e13f07ebbf9bc0

I can't find any official documentation of the Mojang API either, other than http://wiki.vg/Mojang_API but even that doesn't look official. It looks like it's a private API, that's been reverse engineered.

Will investigate further

**Comment by jamiebicknell** [comment]
After further investigation I still can't see any official mentions of the correct URL for the skin, so based on the fact the Amazon S3 URL has worked for around 2 years I'm going to keep it the same for the time being...

However, following the Mojang API (still unsure whether official and/or stable), I can query the API to get the UUID based on username, then query the API again to get textures for that UUID, which returns the correct URL for the skin that doesn't need `FOLLOW_LOCATION` enabled.

The issue with this is this route are:
* 3 HTTP requests instead of just one (increased load time)
* You can request the same profile only once per minute due to the API limit (potential of getting server banned from API)
* Potentially 

The benefits would mean:
* Avatar / skin would show the most up to date version, as current method takes some time to update, and this is the same with other Avatar services like [Minotar.net](https://minotar.net/)
* Username automatic capitalisation fixing so that user doesn't have to enter the username in the exact same case
* Better computability on servers that disallow `FOLLOW_LOCATION`

Another more suitable option would be to just use http://skins.minecraft.net/MinecraftSkins/USERNAME.png and then manually code in the `FOLLOW_LOCATION` bit to get the skin URL directly. The bonus of this too is that it automatically fixes the username capitalisation and doesn't apply to any API limits.

Thanks for bringing this to my attention, I'm going to update the files to use the latter method, and do some serious testing, and also build in support for 3 pixel width arms too, as I seemed to have missed that announcement.

**Comment by SnowPatch** [comment]
Really need the new servers. The skins isn't chaning on amazonaws...

**Comment by jamiebicknell** [comment]
I'll be finishing the code off tomorrow, but I'll need to do some serious testing to make sure it works as it should and there aren't any API limits enforced. So overall probably end of the week before it's on the master branch, providing I don't encounter any issues.

If you need to use it in the meantime and your server allows `FOLLOW_LOCATION` just add that CURL option, and change the old URL on line 18 of face.php and line 16 of skin.php. I can't promise it'll work and can't promise it'll be stable, but until I complete my code and test it full, it's the best I can do.

**Comment by SnowPatch** [comment]
Thanks, it works like a charm when using FOLLOW_LOCATION :)

**Comment by jamiebicknell** [comment]
Yeah, I'm hoping it's not rate limited too. If you do encounter any 404's or messages like that, please do let me know. My solution won't need `FOLLOW_LOCATION` either, which means better compatibility on servers.

**Pull request closed without merging**
